language: generic
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: derreteu.com
  acl: public_read
  on:
    repo: lira/derreteu
  skip_cleanup: true
  local_dir: src
